ScaffoldFoundation/config/routes.rb
Rails.application.routes.draw do
  root 'alumnos#index'
  resources :alumnos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ScaffoldFoundation/app/models/alumno.rb
class Alumno < ApplicationRecord
end

ScaffoldFoundation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ScaffoldFoundation/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :numero_control, :carrera, :anio_ingreso)
    end
end

ScaffoldFoundation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ScaffoldFoundation/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

ScaffoldFoundation/app/helpers/application_helper.rb
module ApplicationHelper
end

ScaffoldFoundation/app/views/alumnos/_form.html.erb
<%= form_for(alumno) do |f| %>
  <% if alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :numero_control %>
    <%= f.number_field :numero_control %>
  </div>

  <div class="field">
    <%= f.label :carrera %>
    <%= f.text_field :carrera %>
  </div>

  <div class="field">
    <%= f.label :anio_ingreso %>
    <%= f.date_select :anio_ingreso %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ScaffoldFoundation/app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Show', @alumno, class:'button radius success' %> |
<%= link_to 'Back', alumnos_path, class:'button radius secondary' %>

ScaffoldFoundation/app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero control</th>
      <th>Carrera</th>
      <th>Anio ingreso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.numero_control %></td>
        <td><%= alumno.carrera %></td>
        <td><%= alumno.anio_ingreso %></td>
        <td><%= link_to 'Show', alumno, class:'button radius' %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno), class:'button radius success' %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' }, class:'button radius alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path, class:'button round success' %>

ScaffoldFoundation/app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Back', alumnos_path, class:'button radius secondary' %>

ScaffoldFoundation/app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Numero control:</strong>
  <%= @alumno.numero_control %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @alumno.carrera %>
</p>

<p>
  <strong>Anio ingreso:</strong>
  <%= @alumno.anio_ingreso %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno), class:'button radius default' %> |
<%= link_to 'Back', alumnos_path, class:'button radius secondary' %>

ScaffoldFoundation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaffoldFoundation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>