Quiz/config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions

  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  post "choices/create"
  post "choices/destroy"
end

Quiz/app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

Quiz/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :choices

  def uncorrect
    choices.each {|c| c.correct = false}
  end

  def answer
    uncorrect
    choices.select {|c| c.correct}[0]
  end

  def answer= choice
    if !answer.nil?
      answer.correct = false
    end
    if choices.include? choice
      choice.correct = true
    else
      choices << choice
      choice.correct = true
    end
  end
end

Quiz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Quiz/app/controllers/concerns/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @question = Question.find(params[:question])
    text = params[:text]
    correct = params[:correct] == '1'
    new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)

    if new.correct
      @question.answer = new
    end

    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question])
    @choice = Choice.find(params[:choice])
    @choice.destroy

    redirect_to question_path(@question)
  end
end

Quiz/app/controllers/concerns/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @questions.sort {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html
      format.xml {render :xml => @questions}
    end
  end

  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def new
    @question = Question.new

    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new (params_question)

    respond_to do |format|
      if @question.save
        format.html {redirect_to(@question, :notice => 'Pregunta agregada exitosamente')}
        format.xml {render :xml => @question, :status => :created, :location => @question}
      else
        format.html {render :action => 'new'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params_question)
        format.html {redirect_to(@question, :notice => 'Pregunta actualizada correctamente')}
        format.xml {head :ok}
      else
        format.html {render :action => 'edit'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html {redirect_to(question_url)}
      format.xml {head :ok}
    end
  end

  private
  def params_question
    params.require(:question).permit(:text)
  end
end

Quiz/app/controllers/concerns/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end

  def start
    total = params[:number].to_i
    all = Question.all.map {|x| x.id}
    session[:questions] = all.sort_by{rand}[0..(total-1)]
    session[:total] = total
    session[:current] = 0
    session[:correct] = 0
    redirect_to :action => 'question'
  end

  def question
    @current = session[:current]
    @total = session[:total]
    if @current >= @total
      redirect_to :action => 'end'
      return
    end
    @question = Question.find(session[:questions][@current])
    @choices = @question.choices.sort_by {rand}
    session[:question] = @question
    session[:choices] = @choices
  end

  def answer
    @current = session[:current]
    @total = session[:total]
    choiceid = params[:choice]
    @question = session[:question]
    @choices = session[:choices]
    @choice = choiceid ? Choice.find(choiceid):nil
    if @choice and @choice.correct == 1
      @correct = true
      session[:correct] += 1
    else
      @correct = false
    end
    session[:current] += 1
  end

  def end
    @correct = session[:correct]
    @total = session[:total]
    @score = @correct * 100 / @total
  end
end

Quiz/app/helpers/application_helper.rb
module ApplicationHelper
end

Quiz/app/helpers/choices_helper.rb
module ChoicesHelper
end

Quiz/app/helpers/questions_helper.rb
module QuestionsHelper
end

Quiz/app/helpers/quiz_helper.rb
module QuizHelper
end

Quiz/app/views/choices/create.html.erb
<h1>Choices#create</h1>
<p>Find me in app/views/choices/create.html.erb</p>

Quiz/app/views/choices/destroy.html.erb
<h1>Choices#destroy</h1>
<p>Find me in app/views/choices/destroy.html.erb</p>

Quiz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Quiz/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, 'error') %>
    prohibited this question from beign saved:
  </h2>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
        <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :text %>
  <%= f.text_area :text, :size => '50x3' %>
</div>
<div class="actions">
  <%= f.submit :class => 'btn btn-success' %>
</div>
<% end %>

Quiz/app/views/questions/edit.html.erb
<h1>Editar Pregunta</h1>
<%= render 'form' %><br/>
<%= link_to 'Consultar', @question, :class => 'btn btn-info' %>
<%= link_to 'Regresar', questions_path, :class => 'btn btn-primary' %>
<% content_for(:title) do %>
Actualizar Pregunta
<% end %>

Quiz/app/views/questions/index.html.erb
<h1>Lista de Preguntas</h1>
<p>Total: <%= @questions.size %></p>
<p><%= link_to'Agregar Pregunta', new_question_path, :class => 'btn btn-success' %></p>
<table class="table">
  <tr>
    <th>Pregunta</th>
    <th>Opciones</th>
    <th colspan="3">Acciones</th>
  </tr>
  <% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
        <li>
          <%= choice.text %>
          <% if choice.correct == 1 %> (correct) <% end %>
        </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Consultar', question, :class => 'btn btn-info' %></td>
    <td><%= link_to 'Editar', edit_question_path(question), :class => 'btn btn-warning' %></td>
    <td><%= link_to 'Eliminar', question, :confirm => '¿Estas seguro que desea eliminar?', :method => :delete, :class => 'btn btn-danger' %></td>
  </tr>
      <% end %>
</table>
<% content_for(:title) do %>
All questions
<% end %>
<%= link_to 'Realizar Quiz', quiz_index_url, :class => 'btn btn-primary' %>

Quiz/app/views/questions/new.html.erb
<h1>Nueva Pregunta</h1>
<%= render 'form' %><br/>

<%= link_to 'Regresar', questions_path, :class => 'btn btn-primary'%>
<% content_for(:title) do %>
New Question
<% end %>

Quiz/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Pregunta:</strong>
  <%= @question.text %>
</p>
<h4>Opciones</h4>
<ul>
  <% @question.choices.find_each do |choice| %>
      <li>
        <%= choice.text %>
        <% if choice.correct == 1 %> (Correct) <% end %>
  <%= form_tag({:controller => 'choices', :action => 'destroy', :class => 'table'}) do %>
      <%= hidden_field_tag :question, @question.id %>
      <%= hidden_field_tag :choice, choice.id %>
      <%= submit_tag 'Eliminar', :class => 'btn btn-xs btn-danger' %>
  <% end %>
  </li>
  <% end %>
</ul>
<h5>Nueva Opción</h5>
<%= form_tag({:controller => 'choices', :action => 'create'}) do %>
    <%= hidden_field_tag :question, @question.id %>
    <%= label_tag :text, 'Valor' %><br />
    <%= text_field_tag :text %><br />
    <%= check_box_tag :correct %><br />
    <br />
      <%= submit_tag('Guardar', :class => 'btn-success') %>
<% end %>
    <br />	  
<%= link_to 'Editar', edit_question_path(@question), :class => 'btn btn-warning' %>
<%= link_to 'Regresar', questions_path, :class => 'btn btn-primary' %>
<% content_for(:title) do %>
    Questions Details
<%end%>

Quiz/app/views/quiz/answer.html.erb
<h1>Pregunta <%= @current + 1 %> de <%= @total %></h1>
<p id="question">
  <%= @question[:text] %>
</p>
<div id="feedback-choices">
  <% @choices.each do |choice| %>

      <%if(choice[:correct])%>
      <p class="correct feedback-choice">
        <%elsif choice == @choice%>
      <p class="incorrect feedback-choice">
          <% else %>
      <p class="feedback-choice">
          <% end %>
      <%= choice[:text] %>
      </p>
      <% end %>
  </div>
<p class="feedback">
  <% if @correct%>
  correct!
      <% else %>
  Incorrect!
      <% end %>
</p>

<%= form_tag({:controller => 'quiz', :action => 'question'}) do %>
    <div class="center">
      <%= submit_tag('Continuar', :class => 'btn btn-success') %>
      </div>
    <% end %>
<% content_for(:title) do%>
    Question <%= @current + 1 %> de <%= @total %>
    <%end%>

Quiz/app/views/quiz/end.html.erb
<h1>Resultados del Quiz</h1>
<p id="question">Respondiste correctamente <%= @correct %> de <%= @total %> preguntas.</p>
<p id="scorre"><%= @score %></p>
<%= form_tag({:controller => 'quiz', :action => 'index'}, :method => 'get') do %>
<div class="center">
  <%= submit_tag('Tomar otro quiz', :class => 'btn btn-success') %>
</div>
<% end %>
<% content_for(:title) do %>
Quiz Results
<% end %>

Quiz/app/views/quiz/index.html.erb
<h1>Comenzar Quiz</h1>
<%= form_tag({:controller => 'quiz', :action => 'start'}) do %>
<p><%= label_tag(:number, '¿Cuantas preguntas desea responder?', :id => 'question') %></p>
<p class="center">
  <%= select_tag(:number, options_for_select((1..10).map{|x| [x, x]}), :id => 'count') %>
</p>
<div class="center">
  <%= submit_tag 'Comenzar', :class => 'btn btn-success'%>
</div>
<%end%>
<% content_for(:title) do %>
Start Quiz
<%end%>

Quiz/app/views/quiz/question.html.erb
<h1>Pregunta <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => 'quiz', :action => 'answer'}) do %>
<% @choices.each do |choice| %>
    <p class="choise">
      <%= radio_button_tag(:choice, choice.id) %>
      <%= label_tag('choice_'.concat(choice.id.to_s).to_sym, choice.text) %>
    </p>
    <% end %>
<div class="center">
  <%= submit_tag('Continuar', :class => 'btn btn-success') %>
</div>
<% end %>

<% content_for(:title) do %>
Question <%= @current + 1 %> of <%= @total %>
<% end %>

Quiz/app/views/quiz/start.html.erb
<h1>Realizar Quiz</h1>
<p>Find me in app/views/quiz/start.html.erb</p>