Foundation/config/routes.rb
Rails.application.routes.draw do
  root 'autos#index'
  resources :autos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

Foundation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Foundation/app/models/auto.rb
class Auto < ApplicationRecord
end

Foundation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Foundation/app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:marca, :modelo, :anio, :precio, :fecha_adquisicion)
    end
end

Foundation/app/helpers/application_helper.rb
module ApplicationHelper
end

Foundation/app/helpers/autos_helper.rb
module AutosHelper
end

Foundation/app/views/autos/_form.html.erb
<%= form_for(auto) do |f| %>
  <% if auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :anio %>
    <%= f.number_field :anio %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :fecha_adquisicion %>
    <%= f.date_select :fecha_adquisicion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Foundation/app/views/autos/edit.html.erb
<h1>Editando Auto</h1>

<%= render 'form', auto: @auto %>

<%= link_to 'Consultar', @auto, class:'button radius success' %> |
<%= link_to 'Regresar', autos_path, class:'button radius secondary' %>

Foundation/app/views/autos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autos</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Año</th>
      <th>Precio</th>
      <th>Fecha adquisicion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autos.each do |auto| %>
      <tr>
        <td><%= auto.marca %></td>
        <td><%= auto.modelo %></td>
        <td><%= auto.anio %></td>
        <td><%= auto.precio %></td>
        <td><%= auto.fecha_adquisicion %></td>
        <td><%= link_to 'Consultar', auto, class:'button radius' %></td>
        <td><%= link_to 'Editar', edit_auto_path(auto), class:'button radius warning' %></td>
        <td><%= link_to 'Eliminar', auto, method: :delete, data: { confirm: '¿Está seguro de eliminar?' }, class:'button radius alert'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Auto', new_auto_path, class:'button round success' %>

Foundation/app/views/autos/new.html.erb
<h1>Nuevo Auto</h1>

<%= render 'form', auto: @auto, class:'button radius default'%>

<%= link_to 'Back', autos_path,class:'button radius secondary' %>

Foundation/app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @auto.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @auto.modelo %>
</p>

<p>
  <strong>Año:</strong>
  <%= @auto.anio %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @auto.precio %>
</p>

<p>
  <strong>Fecha adquisicion:</strong>
  <%= @auto.fecha_adquisicion %>
</p>

<%= link_to 'Editar', edit_auto_path(@auto), class:'button radius warning' %> |
<%= link_to 'Regresar', autos_path,class:'button radius secondary' %>

Foundation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoundationScaffold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>